extract = 'total_dyn_inst: (\d+)'
benchmarks = './tdce/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.dce]
pipeline = [
    "bril2json",
    "python3 dce.py",
    "brili -p {args}",
]
